# Generated by Django 3.2.8 on 2021-10-28 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EpicEvents', '0002_auto_20211027_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='data_updated',
            new_name='date_updated',
        ),
    ]
