# Generated by Django 3.2.8 on 2021-11-04 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EpicEvents', '0006_auto_20211029_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='EpicEvents.client'),
        ),
    ]
